apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubtest
  labels:
    app: javaex
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: kubtest
        image: "markjeffery/kubjavaex:latest"
        env:
        - name: "APPDYNAMICS_CONTROLLER_HOST_NAME"
          value: ""
        - name: "APPDYNAMICS_CONTROLLER_PORT"
          value: ""
        - name: "APPDYNAMICS_AGENT_ACCOUNT_NAME"
          value: ""
        - name: "APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
          value:  ""
        - name: "APPDYNAMICS_AGENT_APPLICATION_NAME"
          value: "kubernetes"
        - name: "APPDYNAMICS_AGENT_TIER_NAME"
          value: "tomcat"
        volumeMounts:
        - mountPath: /AppAgent
          name: app-agent
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["/unregister.sh","unregister"]
      volumes:
      - name: app-agent
        hostPath:
          path: /opt/AppDynamics/AppServerAgent
